#[rustfmt::skip]
#[macro_export]
macro_rules! unroll {
    (0x00, $i:ident, $block:block) => {};
    (0x01, $i:ident, $block:block) => { unroll!(0x00, $i, $block); let $i: usize = 0x00; $block };
    (0x02, $i:ident, $block:block) => { unroll!(0x01, $i, $block); let $i: usize = 0x01; $block };
    (0x03, $i:ident, $block:block) => { unroll!(0x02, $i, $block); let $i: usize = 0x02; $block };
    (0x04, $i:ident, $block:block) => { unroll!(0x03, $i, $block); let $i: usize = 0x03; $block };
    (0x05, $i:ident, $block:block) => { unroll!(0x04, $i, $block); let $i: usize = 0x04; $block };
    (0x06, $i:ident, $block:block) => { unroll!(0x05, $i, $block); let $i: usize = 0x05; $block };
    (0x07, $i:ident, $block:block) => { unroll!(0x06, $i, $block); let $i: usize = 0x06; $block };
    (0x08, $i:ident, $block:block) => { unroll!(0x07, $i, $block); let $i: usize = 0x07; $block };
    (0x09, $i:ident, $block:block) => { unroll!(0x08, $i, $block); let $i: usize = 0x08; $block };
    (0x0a, $i:ident, $block:block) => { unroll!(0x09, $i, $block); let $i: usize = 0x09; $block };
    (0x0b, $i:ident, $block:block) => { unroll!(0x0a, $i, $block); let $i: usize = 0x0a; $block };
    (0x0c, $i:ident, $block:block) => { unroll!(0x0b, $i, $block); let $i: usize = 0x0b; $block };
    (0x0d, $i:ident, $block:block) => { unroll!(0x0c, $i, $block); let $i: usize = 0x0c; $block };
    (0x0e, $i:ident, $block:block) => { unroll!(0x0d, $i, $block); let $i: usize = 0x0d; $block };
    (0x0f, $i:ident, $block:block) => { unroll!(0x0e, $i, $block); let $i: usize = 0x0e; $block };
    (0x10, $i:ident, $block:block) => { unroll!(0x0f, $i, $block); let $i: usize = 0x0f; $block };
    (0x11, $i:ident, $block:block) => { unroll!(0x10, $i, $block); let $i: usize = 0x10; $block };
    (0x12, $i:ident, $block:block) => { unroll!(0x11, $i, $block); let $i: usize = 0x11; $block };
    (0x13, $i:ident, $block:block) => { unroll!(0x12, $i, $block); let $i: usize = 0x12; $block };
    (0x14, $i:ident, $block:block) => { unroll!(0x13, $i, $block); let $i: usize = 0x13; $block };
    (0x15, $i:ident, $block:block) => { unroll!(0x14, $i, $block); let $i: usize = 0x14; $block };
    (0x16, $i:ident, $block:block) => { unroll!(0x15, $i, $block); let $i: usize = 0x15; $block };
    (0x17, $i:ident, $block:block) => { unroll!(0x16, $i, $block); let $i: usize = 0x16; $block };
    (0x18, $i:ident, $block:block) => { unroll!(0x17, $i, $block); let $i: usize = 0x17; $block };
    (0x19, $i:ident, $block:block) => { unroll!(0x18, $i, $block); let $i: usize = 0x18; $block };
    (0x1a, $i:ident, $block:block) => { unroll!(0x19, $i, $block); let $i: usize = 0x19; $block };
    (0x1b, $i:ident, $block:block) => { unroll!(0x1a, $i, $block); let $i: usize = 0x1a; $block };
    (0x1c, $i:ident, $block:block) => { unroll!(0x1b, $i, $block); let $i: usize = 0x1b; $block };
    (0x1d, $i:ident, $block:block) => { unroll!(0x1c, $i, $block); let $i: usize = 0x1c; $block };
    (0x1e, $i:ident, $block:block) => { unroll!(0x1d, $i, $block); let $i: usize = 0x1d; $block };
    (0x1f, $i:ident, $block:block) => { unroll!(0x1e, $i, $block); let $i: usize = 0x1e; $block };
    (0x20, $i:ident, $block:block) => { unroll!(0x1f, $i, $block); let $i: usize = 0x1f; $block };
    (0x21, $i:ident, $block:block) => { unroll!(0x20, $i, $block); let $i: usize = 0x20; $block };
    (0x22, $i:ident, $block:block) => { unroll!(0x21, $i, $block); let $i: usize = 0x21; $block };
    (0x23, $i:ident, $block:block) => { unroll!(0x22, $i, $block); let $i: usize = 0x22; $block };
    (0x24, $i:ident, $block:block) => { unroll!(0x23, $i, $block); let $i: usize = 0x23; $block };
    (0x25, $i:ident, $block:block) => { unroll!(0x24, $i, $block); let $i: usize = 0x24; $block };
    (0x26, $i:ident, $block:block) => { unroll!(0x25, $i, $block); let $i: usize = 0x25; $block };
    (0x27, $i:ident, $block:block) => { unroll!(0x26, $i, $block); let $i: usize = 0x26; $block };
    (0x28, $i:ident, $block:block) => { unroll!(0x27, $i, $block); let $i: usize = 0x27; $block };
    (0x29, $i:ident, $block:block) => { unroll!(0x28, $i, $block); let $i: usize = 0x28; $block };
    (0x2a, $i:ident, $block:block) => { unroll!(0x29, $i, $block); let $i: usize = 0x29; $block };
    (0x2b, $i:ident, $block:block) => { unroll!(0x2a, $i, $block); let $i: usize = 0x2a; $block };
    (0x2c, $i:ident, $block:block) => { unroll!(0x2b, $i, $block); let $i: usize = 0x2b; $block };
    (0x2d, $i:ident, $block:block) => { unroll!(0x2c, $i, $block); let $i: usize = 0x2c; $block };
    (0x2e, $i:ident, $block:block) => { unroll!(0x2d, $i, $block); let $i: usize = 0x2d; $block };
    (0x2f, $i:ident, $block:block) => { unroll!(0x2e, $i, $block); let $i: usize = 0x2e; $block };
    (0x30, $i:ident, $block:block) => { unroll!(0x2f, $i, $block); let $i: usize = 0x2f; $block };
    (0x31, $i:ident, $block:block) => { unroll!(0x30, $i, $block); let $i: usize = 0x30; $block };
    (0x32, $i:ident, $block:block) => { unroll!(0x31, $i, $block); let $i: usize = 0x31; $block };
    (0x33, $i:ident, $block:block) => { unroll!(0x32, $i, $block); let $i: usize = 0x32; $block };
    (0x34, $i:ident, $block:block) => { unroll!(0x33, $i, $block); let $i: usize = 0x33; $block };
    (0x35, $i:ident, $block:block) => { unroll!(0x34, $i, $block); let $i: usize = 0x34; $block };
    (0x36, $i:ident, $block:block) => { unroll!(0x35, $i, $block); let $i: usize = 0x35; $block };
    (0x37, $i:ident, $block:block) => { unroll!(0x36, $i, $block); let $i: usize = 0x36; $block };
    (0x38, $i:ident, $block:block) => { unroll!(0x37, $i, $block); let $i: usize = 0x37; $block };
    (0x39, $i:ident, $block:block) => { unroll!(0x38, $i, $block); let $i: usize = 0x38; $block };
    (0x3a, $i:ident, $block:block) => { unroll!(0x39, $i, $block); let $i: usize = 0x39; $block };
    (0x3b, $i:ident, $block:block) => { unroll!(0x3a, $i, $block); let $i: usize = 0x3a; $block };
    (0x3c, $i:ident, $block:block) => { unroll!(0x3b, $i, $block); let $i: usize = 0x3b; $block };
    (0x3d, $i:ident, $block:block) => { unroll!(0x3c, $i, $block); let $i: usize = 0x3c; $block };
    (0x3e, $i:ident, $block:block) => { unroll!(0x3d, $i, $block); let $i: usize = 0x3d; $block };
    (0x3f, $i:ident, $block:block) => { unroll!(0x3e, $i, $block); let $i: usize = 0x3e; $block };
    (0x40, $i:ident, $block:block) => { unroll!(0x3f, $i, $block); let $i: usize = 0x3f; $block };
    (0,    $i:ident, $block:block) => { unroll!(0x00, $i, $block) };
    (1,    $i:ident, $block:block) => { unroll!(0x01, $i, $block) };
    (2,    $i:ident, $block:block) => { unroll!(0x02, $i, $block) };
    (3,    $i:ident, $block:block) => { unroll!(0x03, $i, $block) };
    (4,    $i:ident, $block:block) => { unroll!(0x04, $i, $block) };
    (5,    $i:ident, $block:block) => { unroll!(0x05, $i, $block) };
    (6,    $i:ident, $block:block) => { unroll!(0x06, $i, $block) };
    (7,    $i:ident, $block:block) => { unroll!(0x07, $i, $block) };
    (8,    $i:ident, $block:block) => { unroll!(0x08, $i, $block) };
    (9,    $i:ident, $block:block) => { unroll!(0x09, $i, $block) };
    (10,   $i:ident, $block:block) => { unroll!(0x0a, $i, $block) };
    (11,   $i:ident, $block:block) => { unroll!(0x0b, $i, $block) };
    (12,   $i:ident, $block:block) => { unroll!(0x0c, $i, $block) };
    (13,   $i:ident, $block:block) => { unroll!(0x0d, $i, $block) };
    (14,   $i:ident, $block:block) => { unroll!(0x0e, $i, $block) };
    (15,   $i:ident, $block:block) => { unroll!(0x0f, $i, $block) };
    (16,   $i:ident, $block:block) => { unroll!(0x10, $i, $block) };
    (17,   $i:ident, $block:block) => { unroll!(0x11, $i, $block) };
    (18,   $i:ident, $block:block) => { unroll!(0x12, $i, $block) };
    (19,   $i:ident, $block:block) => { unroll!(0x13, $i, $block) };
    (20,   $i:ident, $block:block) => { unroll!(0x14, $i, $block) };
    (21,   $i:ident, $block:block) => { unroll!(0x15, $i, $block) };
    (22,   $i:ident, $block:block) => { unroll!(0x16, $i, $block) };
    (23,   $i:ident, $block:block) => { unroll!(0x17, $i, $block) };
    (24,   $i:ident, $block:block) => { unroll!(0x18, $i, $block) };
    (25,   $i:ident, $block:block) => { unroll!(0x19, $i, $block) };
    (26,   $i:ident, $block:block) => { unroll!(0x1a, $i, $block) };
    (27,   $i:ident, $block:block) => { unroll!(0x1b, $i, $block) };
    (28,   $i:ident, $block:block) => { unroll!(0x1c, $i, $block) };
    (29,   $i:ident, $block:block) => { unroll!(0x1d, $i, $block) };
    (30,   $i:ident, $block:block) => { unroll!(0x1e, $i, $block) };
    (31,   $i:ident, $block:block) => { unroll!(0x1f, $i, $block) };
    (32,   $i:ident, $block:block) => { unroll!(0x20, $i, $block) };
    (33,   $i:ident, $block:block) => { unroll!(0x21, $i, $block) };
    (34,   $i:ident, $block:block) => { unroll!(0x22, $i, $block) };
    (35,   $i:ident, $block:block) => { unroll!(0x23, $i, $block) };
    (36,   $i:ident, $block:block) => { unroll!(0x24, $i, $block) };
    (37,   $i:ident, $block:block) => { unroll!(0x25, $i, $block) };
    (38,   $i:ident, $block:block) => { unroll!(0x26, $i, $block) };
    (39,   $i:ident, $block:block) => { unroll!(0x27, $i, $block) };
    (40,   $i:ident, $block:block) => { unroll!(0x28, $i, $block) };
    (41,   $i:ident, $block:block) => { unroll!(0x29, $i, $block) };
    (42,   $i:ident, $block:block) => { unroll!(0x2a, $i, $block) };
    (43,   $i:ident, $block:block) => { unroll!(0x2b, $i, $block) };
    (44,   $i:ident, $block:block) => { unroll!(0x2c, $i, $block) };
    (45,   $i:ident, $block:block) => { unroll!(0x2d, $i, $block) };
    (46,   $i:ident, $block:block) => { unroll!(0x2e, $i, $block) };
    (47,   $i:ident, $block:block) => { unroll!(0x2f, $i, $block) };
    (48,   $i:ident, $block:block) => { unroll!(0x30, $i, $block) };
    (49,   $i:ident, $block:block) => { unroll!(0x31, $i, $block) };
    (50,   $i:ident, $block:block) => { unroll!(0x32, $i, $block) };
    (51,   $i:ident, $block:block) => { unroll!(0x33, $i, $block) };
    (52,   $i:ident, $block:block) => { unroll!(0x34, $i, $block) };
    (53,   $i:ident, $block:block) => { unroll!(0x35, $i, $block) };
    (54,   $i:ident, $block:block) => { unroll!(0x36, $i, $block) };
    (55,   $i:ident, $block:block) => { unroll!(0x37, $i, $block) };
    (56,   $i:ident, $block:block) => { unroll!(0x38, $i, $block) };
    (57,   $i:ident, $block:block) => { unroll!(0x39, $i, $block) };
    (58,   $i:ident, $block:block) => { unroll!(0x3a, $i, $block) };
    (59,   $i:ident, $block:block) => { unroll!(0x3b, $i, $block) };
    (60,   $i:ident, $block:block) => { unroll!(0x3c, $i, $block) };
    (61,   $i:ident, $block:block) => { unroll!(0x3d, $i, $block) };
    (62,   $i:ident, $block:block) => { unroll!(0x3e, $i, $block) };
    (63,   $i:ident, $block:block) => { unroll!(0x3f, $i, $block) };
    (64,   $i:ident, $block:block) => { unroll!(0x40, $i, $block) };
}
